-- DB backup (schema + data)
-- Created: 2026-05-07
-- Generated by assistant: combined remote schema and supabase/seed.sql

-- ===== remote schema (supabase/migrations/20260507120723_remote_schema.sql) =====
alter table "public"."attendance_records" drop constraint "attendance_records_status_check";

alter table "public"."system_logs" drop constraint "system_logs_action_check";

alter table "public"."users" drop constraint "users_role_check";

alter table "public"."attendance_records" add constraint "attendance_records_status_check" CHECK (((status)::text = ANY (ARRAY['present'::text, 'late'::text, 'absent'::text, 'excused'::text]))) not valid;

alter table "public"."attendance_records" validate constraint "attendance_records_status_check";

alter table "public"."system_logs" add constraint "system_logs_action_check" CHECK (((action)::text = ANY ((ARRAY['login'::character varying, 'logout'::character varying, 'scan_qr'::character varying, 'attendance_record'::character varying, 'create_class'::character varying, 'update_class'::character varying, 'delete_class'::character varying, 'add_student'::character varying, 'remove_student'::character varying, 'generate_qr'::character varying, 'update_user'::character varying, 'delete_user'::character varying, 'other'::character varying])::text[]))) not valid;

alter table "public"."system_logs" validate constraint "system_logs_action_check";

alter table "public"."users" add constraint "users_role_check" CHECK (((role)::text = ANY ((ARRAY['admin'::character varying, 'professor'::character varying, 'student'::character varying])::text[]))) not valid;

alter table "public"."users" validate constraint "users_role_check";

-- ===== seed data (supabase/seed.sql) =====
SET session_replication_role = replica;

--
-- PostgreSQL database dump
--

-- \restrict o96jFOMVUa7nZxRL6mznpmKqXEfXuHSuToGq0ZlJ9H8KUasWOxuv7zaOvJfpGp1

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- (data inserts follow)

INSERT INTO "public"."users" ("id", "name", "email", "email_verified_at", "password", "remember_token", "created_at", "updated_at", "role", "username", "student_id", "is_active") VALUES
	(2, 'Karlo Dalangin', 'karlo@gmail.com', NULL, '$2y$12$PsAQn5hXca4kFfuve0fYU.T.4YNt/gbKYQBdYZo2srEHDbgTMmda6', NULL, '2026-05-05 16:36:36', '2026-05-05 16:36:36', 'professor', 'karlo', NULL, true),
	(5, 'Steven Edward Barba', 'steven@gmail.com', NULL, '$2y$12$1OhsZzzOOjKytP1f6LopguEw.XnygMWeHkiax0xLWUoamY3ee.6ZW', NULL, '2026-05-05 16:45:35', '2026-05-06 02:07:13', 'student', 'steven', NULL, true),
	(6, 'Ramil Agne II', 'Ramil@gmail.com', NULL, '$2y$12$7pMeflqn774neWnZz/FyHe4Fl5NJKX8MByQBL2nMr2fWWSVJRbJpu', NULL, '2026-05-06 02:12:00', '2026-05-06 02:12:00', 'professor', 'Ramil', NULL, true),
	(7, 'Gabriel Jana', 'gab@gmail.com', NULL, '$2y$12$M0t//1zm8HI3sZwPuzolgOuXAMHbPWXdXJVy0fdEqhN9OfHauup3C', NULL, '2026-05-06 02:20:51', '2026-05-06 02:20:51', 'student', 'Gab', NULL, true),
	(9, 'Admin User', 'admin@example.com', NULL, '$2y$12$w.A.95.PeYUWifc1osIBku9xQeR8Y10uqHOr6GkgWOmrGFbzzs6oK', NULL, '2026-05-06 17:16:55', '2026-05-06 17:19:20', 'admin', 'admin', NULL, true),
	(10, 'Hugo Lita', 'hugo@gmail.com', NULL, '$2y$12$inXAkjZytc.FKLlfsQiPQug.LA6oc8//lv7WtY1GQs7iLu5qDwusG', NULL, '2026-05-06 11:00:27', '2026-05-06 11:00:27', 'professor', 'hugo', NULL, true);

INSERT INTO "public"."classes" ("id", "code", "name", "description", "professor_id", "student_count", "is_active", "created_at", "updated_at") VALUES
	(2, 'F102', 'CHASIS', 'Class about chasis', 6, 0, true, '2026-05-06 02:09:49', '2026-05-06 02:12:58'),
	(4, 'F104', 'TURBO CHARGER', 'stutututu', 6, 0, true, '2026-05-06 02:13:33', '2026-05-06 02:13:33'),
	(3, 'F103', 'F103 - Internal Engine Combustion (ICE)', 'broobvrrr', 2, 0, true, '2026-05-06 02:11:01', '2026-05-06 16:26:22'),
	(1, 'F101', 'F101 - AERODYNAMICS', 'basta aero', 2, 0, true, '2026-05-05 16:51:35', '2026-05-06 18:24:41');

INSERT INTO "public"."qr_codes" ("id", "uuid", "class_id", "professor_id", "is_used", "used_at", "expires_at", "created_at", "updated_at", "student_id", "code") VALUES
	(2, '4e122cf6-8f33-4f33-99ce-12ad88a0cd4c', NULL, NULL, false, NULL, NULL, '2026-05-05 16:45:35', '2026-05-05 16:45:35', 5, '{"type":"student_attendance","student_id":5,"student_name":"just","student_email":"just@example.com","generated_at":"2026-05-05T16:45:35+00:00"}'),
	(3, 'bf7fad73-ec0d-47b0-b75f-f394ef43afb6', NULL, NULL, false, NULL, NULL, '2026-05-06 02:20:52', '2026-05-06 02:20:52', 7, NULL);

INSERT INTO "public"."attendance_records" ("id", "class_id", "student_id", "qr_code_id", "status", "minutes_late", "recorded_at", "created_at", "updated_at") VALUES
	(7, 1, 5, NULL, 'present', 0, '2026-05-06 16:33:55', '2026-05-06 16:33:55', '2026-05-06 16:33:55'),
	(9, 3, 7, NULL, 'absent', 0, '2026-05-06 16:30:00', '2026-05-06 16:47:32', '2026-05-06 16:47:32'),
	(10, 1, 7, NULL, 'absent', 0, '2026-05-06 16:45:00', '2026-05-06 16:47:33', '2026-05-06 16:47:33'),
	(8, 3, 5, NULL, 'late', 25, '2026-05-07 00:30:00', '2026-05-06 16:47:31', '2026-05-06 11:04:58');

-- cache and other inserts omitted for brevity (seed.sql contains many more statements)
