<?php


namespace App\Models;

/**
 * @property int $id
 * @property string $name
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $role
 * @property string|null $student_id
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @method \Illuminate\Database\Eloquent\Relations\HasMany classes()
 * @method \Illuminate\Database\Eloquent\Relations\BelongsToMany assignedClasses()
 * @method \Illuminate\Database\Eloquent\Relations\BelongsToMany enrolledClasses()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany qrCodes()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany attendanceRecords()
 * @method \Illuminate\Database\Eloquent\Relations\HasMany logs()
 * @method bool isProfessor()
 * @method bool isAdmin()
 * @method bool isStudent()
 */

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    // Relationship for professors to their classes as the primary instructor
    public function classes(): HasMany
    {
        return $this->hasMany(Classe::class, 'professor_id');
    }

    // Relationship for professors assigned to classes through the pivot table
    public function assignedClasses(): BelongsToMany
    {
        return $this->belongsToMany(Classe::class, 'class_professor', 'professor_id', 'class_id')
            ->withTimestamps();
    }

    // Relationship for students to their enrolled classes
    public function enrolledClasses(): BelongsToMany
    {
        return $this->belongsToMany(Classe::class, 'class_student', 'student_id', 'class_id')
            ->withTimestamps();
    }

    // Relationship for all QR codes generated by professor
    public function qrCodes(): HasMany
    {
        return $this->hasMany(QRCode::class, 'professor_id');
    }

    // Relationship for student's personal QR code
    public function studentQrCode(): HasOne
    {
        return $this->hasOne(QRCode::class, 'student_id');
    }

    // Relationship for attendance records
    public function attendanceRecords(): HasMany
    {
        return $this->hasMany(AttendanceRecord::class, 'student_id');
    }

    // Relationship for system logs
    public function logs(): HasMany
    {
        return $this->hasMany(SystemLog::class);
    }

    public function isProfessor(): bool
    {
        return $this->role === 'professor';
    }

    public function isAdmin(): bool
    {
        return $this->role === 'admin';
    }

    public function isStudent(): bool
    {
        return $this->role === 'student';
    }
}
